### ISSUE TITLE
Visualisierung mit LIN funktioniert nicht mehr

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-cce#12]
Es kommt das Zwischenfenster mit der Meldung
`"Bitte warten - Datenübertragung läuft"`
aber diese Meldung bleibt stehten, obwohl nur ganz wenige Datensätze im Sammelbehälter liegen.

**Comment by huhwt** [comment]
Kann ich nicht bestätigen - sowohl localhost als auch Web-Präsenz laufen wie erwartet. (Eventuell Folgefehler eines anderen Issues, dort gefixt)
