### ISSUE TITLE
Reducir el nombre del módulo.

### ISSUE THREAD

**Issue by BernatBanyuls** [huhwt/huhwt-cce#19]
Quisiera reducir el nombre del módulo en el menú. Como se ve en las imágenes, resulta un texto muy extenso. Si como autor no deseas cambiarlo, agradecería me informaras si hay algún método para hacerlo por mí mismo en mi página.

![error H Hwt_1](https://github.com/huhwt/huhwt-cce/assets/103060233/7e8d41e1-8189-48da-ac38-9c3da229b1a1)

Gracias.

**Comment by huhwt** [comment]
A new release is in the works, so the module identifier will be shorter...
The module identifier is set in 2 places:

`ClippingsCartEnhanced.php`

Line 324
`$this->huh = json_decode('"\u210D"') . "&" . json_decode('"\u210D"') . "wt";`

Line 2104
`return $this->huh . ' ' . I18N::translate(self::CUSTOM_TITLE);`

changing line 324 like this ...
`
$this->huh = json_decode('"\u210D"'); //. "&" . json_decode('"\u210D"') . "wt";
`
... shortens the "logo" to 1 character.

I'm wondering that the module identifier still appears with English text; it should actually be displayed translated - in the translation module (e.g. `es.po`) it is the 2nd entry.

**Comment by BernatBanyuls** [comment]
Gracias por tu ayuda.

Ahora lo tengo perfecto! (Nombre “corto” al menú)



 

Respecto a la traducción, no se a qué te refieres. Este es el texto que veo en el fichero es.po



 

Si te refieres a la línea 2 que está “vacia” la traducción  al español sería “CARRO DE RECORTES”

 

Gracias por todo!

 

 

 

 

Abans d'imprimir aquest correu, penseu si és necessari.

Aquest correu electrònic pot contenir informació confidencial o legalment protegida i està exclusivament adreçat a la persona o entitat destinatària. Si no sou el destinatari final o la persona encarregada de recollir-lo, no esteu autoritzat a llegir-lo, retenir-lo, modificar-lo, distribuir-lo, copiar-lo ni a revelar-ne el contingut. Si heu rebut aquest correu electrònic per error, us preguem que informeu el remitent i elimineu del vostre sistema el missatge i el material annex que pugui contenir. 
Gràcies per la vostra col·laboració.

 

De: EW.H ***@***.***> 
Enviat: dilluns, 19 de febrer de 2024 11:22
Per a: huhwt/huhwt-cce ***@***.***>
A/c: BernatBanyuls ***@***.***>; Author ***@***.***>
Tema: Re: [huhwt/huhwt-cce] Reducir el nombre del módulo. (Issue #19)

 

A new release is in the works, so the module identifier will be shorter...
The module identifier is set in 2 places:

ClippingsCartEnhanced.php

Line 324
$this->huh = json_decode('"\u210D"') . "&" . json_decode('"\u210D"') . "wt";

Line 2104
return $this->huh . ' ' . I18N::translate(self::CUSTOM_TITLE);

changing line 324 like this ...
$this->huh = json_decode('"\u210D"'); //. "&" . json_decode('"\u210D"') . "wt";
... shortens the "logo" to 1 character.

I'm wondering that the module identifier still appears with English text; it should actually be displayed translated - in the translation module (e.g. es.po) it is the 2nd entry.
