### ISSUE TITLE
Einzelne Datensätze löschen

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-cce#6]
Wenn man im Punkt "Löschen" den Punkt "Einzelne Datensätze löschen" auswählt, dann kommt die Meldung "Aktion 'Datensätze zum Löschen auswählen:' geht nicht - ist noch nicht eingebaut", aber war schon immer eingebaut. In der normalen Anzeige des Inhalts des Sammelbehälters kann man jeden einzelnen Datensatz löschen. Dorthin hat der Menüpunkt früher verzweigt.

**Comment by huhwt** [comment]
Ja, stimmt, die Überlegung dahinter ist, dass es eine zusätzliche Ansicht geben soll, in der man die zu löschenden Datensätzen anders als in der allgemeinen Übersicht angezeigt bekommt und auswählen kann ... Solange es eine solche Funktion nicht gibt, sollte ich die Option wohl einfach nicht mit anzeigen?

**Comment by hartenthaler** [comment]
Doch die Option kann angezeigt werden, aber solange sie nicht auf eine neue Spezialseite führt, kann sie doch einfach auf die Sammelbehälteranzeigeseite führen. Wenn es eine Speziallöschseite geben sollte, kann man die Löschfunktion auf der Anzeigeseite natürlich rausnehmen.

**Comment by hartenthaler** [comment]
Ist dieser Punkt nicht inzwischen erledigt?
