### ISSUE TITLE
Sammelaktionen - Error

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-cce#8]
Die Idee mit den Sammelaktionen und die Möglichkeit diese rückgängig zu machen, ist super gut!

Ich habe eine Aktion ausgeführt und will diese nun löschen. dabei kommt eine Fehlermeldung:
`Class "HuHwt\WebtreesMods\ClippingsCartEnhanced\RebuildCart" not found …/modules_v4/huhwt-cce/ClippingsCartEnhanced.php:1518`

**Comment by huhwt** [comment]
fixed
