### ISSUE TITLE
Option Zeilenende macht nur im Zusammenhang mit dem GEDCOM-Export Sinn

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-cce#9]
Die Zeile "Zeilenenden CR/LF (windows) LF (unix)" macht nur im obersten Block mit den Optionen zum GEDCOM-Export Sinn. Ganz unter- und außerhalb des Menüblocks ist die Zeile deplatziert.

**Comment by huhwt** [comment]
bin ich mir nicht ganz sicher - es werden durchaus auch in anderem Kontext Text-Informationen ausgegeben ... werde ich bei Gelegenheit prüfen, bleibt erst mal drin.
